# Generated by Django 3.2.12 on 2023-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_materialdeclientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdeclientes',
            name='material',
            field=models.ImageField(upload_to='material_apoio/clientes/%Y/%m', verbose_name='Material do Cliente'),
        ),
    ]
