# Generated by Django 3.2.12 on 2023-03-30 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
        ('core', '0007_alter_materialdeclientes_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='academia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='academias.academia', verbose_name='Academia'),
        ),
    ]
