from django.urls import path
from django.conf.urls import handler404, handler500, handler403, handler400
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    # path('', login_required(views.Redirecionador.as_view(), login_url='/login'), name="redirecionador"),
    path('', views.Index.as_view(), name="index"),
    path('seja-bem-vindo', login_required(views.Index_2.as_view(), login_url='/login'), name="index_2"),
    path('video_explicativo', login_required(views.VideoExplicativo.as_view(), login_url='/login'), name="video_explicativo"),
    path('video_explicativo_confirm', login_required(views.VideoExplicativoConfirm.as_view(), login_url='/login'), name="video_explicativo_confirm"),
    path('login', views.Login, name="login"),
    path('login_alternativo', views.Login_alternativo, name="login_alternativo"),
    path('cadastro_alternativo', views.Cadastro_alternativo, name="cadastro_alternativo"),
    path('cadastro', views.cadastro, name="cadastro"),
    path('logout', views.Logout, name="logout"),
    path('dados_pessoais', login_required(views.DadosPessoais.as_view(), login_url='/login'), name="dados_pessoais"),
    path('doencas', login_required(views.Doenca.as_view(), login_url='/login'), name="doencas"),
    path('medicamentos', login_required(views.Medicamento.as_view(), login_url='/login'), name="medicamentos"),
    path('cirurgia', login_required(views.Cirurgia.as_view(), login_url='/login'), name="cirurgia"),
    path('exame_de_sangue', login_required(views.ExameDeSangue.as_view(), login_url='/login'), name="exame_sangue"),
    path('intestino', login_required(views.Intestino.as_view(), login_url='/login'), name="intestino"),
    path('sono', login_required(views.Sono.as_view(), login_url='/login'), name="sono"),
    path('alcool', login_required(views.Alcool.as_view(), login_url='/login'), name="alcool"),
    path('suplementos', login_required(views.Suplementos.as_view(), login_url='/login'), name="suplementos"),
    path('ciclos_menstruais', login_required(views.CiclosMenstruais.as_view(), login_url='/login'), name="ciclos_menstruais"),
    path('dados_atropometricos', login_required(views.DadosAntropometricos.as_view(), login_url='/login'), name="dados_atropometricos"),
    path('horarios', login_required(views.Horarios.as_view(), login_url='/login'), name="horarios"),
    path('exercicios', login_required(views.Exercicios.as_view(), login_url='/login'), name="exercicios"),
    path('red_avaliacao', login_required(views.RedirecionadorAvaliacao.as_view(), login_url='/login'), name="red_avaliacao"),
    path('avaliacao', login_required(views.Avaliacao.as_view(), login_url='/login'), name="avaliacao"),
    path('meus_planos_alimentares', views.ExibeAvaliacaoTreino.as_view(), name="baixar_avaliacao"),
    path('meus_planos_alimentares_sem_treino', views.ExibeAvaliacaoSemTreino.as_view(), name="baixar_avaliacao_sem_treino"),
    path('user_infos', login_required(views.UserInfos.as_view(), login_url='/login'), name="user_infos"),
    path('confirmacao', login_required(views.Confirmacao.as_view(), login_url='/login'), name="confirmacao"),
    path('material_apoio', login_required(views.MaterialApoio.as_view(), login_url='/login'), name="material_apoio"),
    path('material_apoio_categoria/<str:categoria>', login_required(views.CategoriaMaterialApoio.as_view(), login_url='/login'), name="categoria_material_apoio"),
    path('material_apoio_busca', login_required(views.BuscaMaterialApoio.as_view(), login_url='/login'), name="busca_material_apoio"),
    path('criando_plano', login_required(views.TelaCarregamento.as_view(), login_url='/login'), name="criando_plano"),
    path('graficos_de_evolucao', login_required(views.Evolucao.as_view(), login_url='/login'), name="tela_evolucao"),
    path('minha_avaliacao_nutricional', login_required(views.RelatorioEvolucaoNew.as_view(), login_url='/login'), name="relatorio_evolucao"),
    #path('minha_avaliacao_nutricional', login_required(views.RelatorioEvolucao.as_view(), login_url='/login'), name="relatorio_evolucao"),
    path('checkout', login_required(views.Checkout.as_view(), login_url='/login'), name="checkout"),
    path('calculadora_de_peso_ideal', login_required(views.Calculadora.as_view(), login_url='/login'), name="calculadora"),
    path('termos_e_condicoes', views.TermosCondicoes.as_view(), name="termos_e_condicoes"),
    path('recuperar_senha', views.RecuperarSenha.as_view(), name="recuperar_senha"),
    # path('evolucao_final', views.EvolucaoFinal.as_view(), name="evolucao_final"),
    path('evolucao_final', views.CapaRelatorioView.as_view(), name="evolucao_final"),
    path('excluir/usuario', views.ExcluirUsuario.as_view(), name="excluir_usuario"),
    path("salvar_imagem", views.salvar_imagem, name="salvar_imagem"),
    path("materiais_usuario", views.MateriaisUsuario.as_view(), name="materiais_usuario"),
    path("gerar-pdf/", views.gerar_pdf, name="gerar_pdf"),
    
    path('relatorio-capa/', views.CapaRelatorioView.as_view(), name='evo_capa'),
    path('avn/', views.RelatorioEvolucaoNew.as_view(), name='teste_capa'),
    path('calculadora_test/', views.Calculadora_test.as_view(), name='teste_capa'),
    path('descargar/', views.descargar_archivo, name='descargar_archivo'),
]
handler404 = views.error_404
handler500 = views.error_500
