# Generated by Django 3.2.12 on 2023-03-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academia',
            name='id',
        ),
        migrations.AlterField(
            model_name='academia',
            name='cnpj',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
