# Generated by Django 3.2.12 on 2023-03-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0003_academia_dia_expiracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academia',
            name='dia_expiracao',
        ),
        migrations.AddField(
            model_name='academia',
            name='dias_restantes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
