# Generated by Django 3.2.12 on 2023-03-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0005_auto_20230331_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='avaliacoes_disponiveis',
            field=models.IntegerField(default=0),
        ),
    ]
