# Generated by Django 3.2.13 on 2022-08-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospessoais',
            name='assistiu_video',
            field=models.BooleanField(default=False, verbose_name='Assistiu o video?'),
        ),
    ]
