# Generated by Django 3.2.12 on 2023-03-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0002_auto_20230331_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='dia_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
