# Generated by Django 3.2.12 on 2023-03-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0004_auto_20230331_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academia',
            name='dias_restantes',
        ),
        migrations.AddField(
            model_name='academia',
            name='dia_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
