# Generated by Django 3.2.13 on 2022-08-03 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMaterialDeApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Categoria')),
                ('palavras_chave', models.TextField(verbose_name='Palavras Chave (Separadas por Espaço)')),
            ],
            options={
                'verbose_name_plural': 'Categorias De Materiais',
            },
        ),
        migrations.CreateModel(
            name='DashBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_1', models.CharField(max_length=255, verbose_name='Título 1')),
                ('subtitulo_1', models.CharField(max_length=255, verbose_name='Subtítulo 1')),
                ('texto_1', models.TextField(verbose_name='Texto 1')),
                ('texto_2', models.TextField(verbose_name='Texto 2')),
                ('texto_3', models.TextField(verbose_name='Texto 3')),
                ('titulo_2', models.CharField(max_length=255, verbose_name='Título 2')),
                ('subtitulo_2', models.CharField(max_length=255, verbose_name='Subtítulo 2')),
                ('link_video', models.CharField(max_length=255, verbose_name='Link para o Video')),
                ('tamanho_titulo', models.CharField(choices=[('t22', 'Tamanho 22'), ('t24', 'Tamanho 24'), ('t26', 'Tamanho 26'), ('t28', 'Tamanho 28'), ('t30', 'Tamanho 30'), ('t35', 'Tamanho 35'), ('t40', 'Tamanho 40')], default='t30', max_length=3, verbose_name='Tamanho do título')),
                ('tamanho_subtitulo', models.CharField(choices=[('t18', 'Tamanho 18'), ('t20', 'Tamanho 20'), ('t22', 'Tamanho 22'), ('t24', 'Tamanho 24'), ('t26', 'Tamanho 26')], default='t24', max_length=3, verbose_name='Tamanho do subtítulo')),
                ('tamanho_texto', models.CharField(choices=[('t14', 'Tamanho 14'), ('t16', 'Tamanho 16'), ('t18', 'Tamanho 18'), ('t20', 'Tamanho 20'), ('t22', 'Tamanho 22')], default='t14', max_length=3, verbose_name='Tamanho do texto')),
            ],
        ),
        migrations.CreateModel(
            name='PaginaInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_1', models.TextField(blank=True, null=True, verbose_name='Mensagem 1')),
                ('mensagem_2', models.TextField(blank=True, null=True, verbose_name='Mensagem 2')),
                ('mensagem_3', models.TextField(blank=True, null=True, verbose_name='Mensagem 3')),
                ('mensagem_4', models.TextField(blank=True, null=True, verbose_name='Mensagem 4')),
            ],
            options={
                'verbose_name_plural': 'Pagina Inicial',
            },
        ),
        migrations.CreateModel(
            name='PlanoAlimentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='Usuário')),
                ('pescoco', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pescoço (cm)')),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cintura (cm)')),
                ('quadril', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quadril (cm)')),
                ('pulso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pulso (cm)')),
                ('abdomen', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Abdômen (cm)')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (kg)')),
                ('percentual_gordura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Gordura')),
                ('gordura_corporal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Gordura Corporal')),
                ('treino', models.CharField(choices=[('s', 'Sim'), ('n', 'Não')], max_length=20, verbose_name='Treino')),
                ('horario_treino', models.TimeField(verbose_name='Horário de Treino')),
                ('café_da_manha', models.TimeField(verbose_name='Horário do café da manhã')),
                ('almoco', models.TimeField(blank=True, null=True, verbose_name='Horário do almoço')),
                ('lanche_1', models.TimeField(blank=True, null=True, verbose_name='Lanche_1')),
                ('lanche_2', models.TimeField(blank=True, null=True, verbose_name='Lanche_2')),
                ('lanche_3', models.TimeField(blank=True, null=True, verbose_name='Lanche_3')),
                ('horario_janta', models.TimeField(blank=True, null=True, verbose_name='Horário de Janta')),
                ('data_realizacao', models.DateField(verbose_name='Data de realização da avaliação')),
                ('kcal', models.IntegerField(verbose_name='Kcal Com Treino')),
                ('kcal_simples', models.IntegerField(default=True, null=True, verbose_name='Kcal Sem Treino')),
            ],
        ),
        migrations.CreateModel(
            name='Termos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo_de_uso', models.TextField(verbose_name='Termo de Uso')),
            ],
            options={
                'verbose_name_plural': 'Termos e Condições de uso',
            },
        ),
        migrations.CreateModel(
            name='Variaveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_1', models.FloatField(verbose_name='Variável 1')),
                ('var_2', models.FloatField(verbose_name='Variável 2')),
                ('var_3', models.FloatField(verbose_name='Variável 3')),
                ('var_4', models.FloatField(verbose_name='Variável 4')),
                ('var_5', models.FloatField(verbose_name='Variável 5')),
                ('var_6', models.FloatField(verbose_name='Variável 6')),
            ],
            options={
                'verbose_name_plural': 'Variáveis',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=555, verbose_name='LINK')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Usuário')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('repetir_senha', models.CharField(max_length=255, verbose_name='Insira a Senha Novamente')),
                ('avaliacoes', models.IntegerField(default=0, verbose_name='Avaliações restantes')),
                ('tipo_plano', models.IntegerField(default=0, verbose_name='Pacote contratado')),
                ('dias_restantes', models.CharField(default='', max_length=255, verbose_name='Dias de acesso')),
                ('alcool', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.alcool')),
                ('ciclo_menstrual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.ciclomenstrual')),
                ('cirurgias', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.cirurgia')),
                ('dados_atropometricos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.antropometricos')),
                ('dados_pessoais', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.dadospessoais')),
                ('doencas', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.doenca')),
                ('exame_sangue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.examesangue')),
                ('exercicios', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.exercicios')),
                ('horarios', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.horarios')),
                ('intestino', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.intestino')),
                ('medicamentos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.medicamento')),
                ('sono', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.sono')),
                ('suplementos', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categorias.suplemento')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDeApoio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_material', models.ImageField(upload_to='material_apoio/imgs/%Y/%m', verbose_name='Imagem do Material')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Material')),
                ('texto', models.TextField(verbose_name='Texto do Material')),
                ('material', models.FileField(upload_to='material_apoio/pdf/%Y/%m', verbose_name='Material de Apoio')),
                ('categoria', models.CharField(choices=[('Geral', 'Geral'), ('Especifico', 'Especifico')], max_length=300)),
                ('palavras_chave_material', models.TextField(verbose_name='Palavras Chave (Separadas por Espaço)')),
                ('categoria_do_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoriamaterialdeapoio', verbose_name='Categoria do material')),
            ],
            options={
                'verbose_name_plural': 'Materiais de Apoio',
            },
        ),
    ]
