# Generated by Django 3.2.13 on 2022-08-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_planoalimentar_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoalimentar',
            name='teste',
        ),
    ]
