# Generated by Django 3.2.12 on 2023-01-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuario_assistiu_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialdeClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255, verbose_name='Usuário')),
                ('categoria', models.CharField(max_length=255, verbose_name='Categoria')),
                ('material', models.FileField(upload_to='material_apoio/clientes/%Y/%m', verbose_name='Material do Cliente')),
                ('data_criacao', models.DateField(verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name_plural': 'Materiais dos Clientes',
            },
        ),
    ]
