# Generated by Django 3.2.12 on 2023-04-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academias', '0006_academia_avaliacoes_disponiveis'),
        ('core', '0008_usuario_academia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='academia',
            field=models.ForeignKey(default=9999999999999999, on_delete=django.db.models.deletion.DO_NOTHING, to='academias.academia', verbose_name='Academia'),
        ),
    ]
